#include <TestingUtil.hpp>

using namespace dplgrammar;

PARSER_TEST("replace_with.dpl") {
    std::vector<int> expectedNodeRules = {
        DplParser::RuleStm,
        DplParser::RuleAssignstm,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleTable,
        DplParser::RuleList,
        DplParser::RuleArgs,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleList,
        DplParser::RuleArgs,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleList,
        DplParser::RuleArgs,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleStm,
        DplParser::RuleAssignstm,
        DplParser::RuleExpr,
        DplParser::RuleTablecall,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleUnaryexpr,
        DplParser::RuleCompareopr,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleStm,
        DplParser::RuleReplacestm,
        DplParser::RuleExpr,
        DplParser::RuleListcall,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleExpr,
        DplParser::RuleExpr,
        DplParser::RuleListcall,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleArthexpr,
        DplParser::RuleExpr,
        DplParser::RuleListcall,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleStm,
        DplParser::RuleAssignstm,
        DplParser::RuleExpr,
        DplParser::RuleTablecall,
        DplParser::RuleTablecall,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleUnaryexpr,
        DplParser::RuleCompareopr,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleExpr,
        DplParser::RuleLiteral,
        DplParser::RuleStm,
        DplParser::RuleExpr,
        DplParser::RuleProccall,
        DplParser::RuleArgs,
        DplParser::RuleExpr
    };
    
    util::TestingUtil::testParser("replace_with.dpl", expectedNodeRules);
}