name: Linting
on:
    workflow_dispatch:
    push:
        branches: [main]
        paths: ['**.cpp', '**.hpp']

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    permissions: # (1)!
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Code
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'google'
          tidy-checks: 'cppcoreguidelines-*,modernize-*'
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}

      - name: Fail fast
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1