name: Linting
on:
  pull_request:
    branches: [main]
    paths: ['**/*.cpp', '**/*.hpp', '!lib/**']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'
          tidy-checks: 'boost-*,bugprone-*,performance-*,readability-*,portability-*,clang-analyzer-*,cppcoreguidelines-*'
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          format-review: true
      - name: Fail Fast
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1